title: Brandon Williams

email: bwilliams9@pm.me

description: ðŸ¤™

repository: bmwilly/bmwilly.github.io
url: "https://bmwilly.github.io"
baseurl: ""
github_username: bmwilly

# Build settings
theme: jekyll-theme-hacker

plugins:
  - jekyll-feed
  - jekyll-analytics
  - jekyll-target-blank

google_analytics: G-GLKSLXZ2GC
